### PR TITLE
Fix Guest Users

### PR DESCRIPTION
**Pull request by AIC-BV**
remove unique:users onRegister to fix User guest accounts
See: wintercms#28

### CODE REVIEW

**Comment by mjauvin** [comment]
You would need to add the rule conditionally like here under complex conditional validation:

https://wintercms.com/docs/services/validation#conditionally-adding-rules

**Comment by AIC-BV** [comment]
Ok I added sometimes

**Comment by mjauvin** [comment]
I had something more like this in mind:
```
$rules['email'] = 'required|between:6,255|email';

$validation->sometimes('email', 'required|between:6,255|email|unique', function($input) {
    return \Winter\User\Models\User::where('email', $input->email)->where('is_guest', 0)->first() !== null;
});
```
Not sure if there's a better way to achieve the same

**Comment by bennothommo** [comment]
I'm going to close this and implement the validation here as Rule objects. This implementation is essentially checking the uniqueness of the email twice (once for the "sometimes" callback, and another with the `unique` rule that it adds), and also doesn't cover when usernames are used instead of email addresses for logins.

Thanks for the submission though, @AIC-BV.

**Comment by AIC-BV** [comment]
@bennothommo 
Does this mean it won't be implemented?
It is required to make the user plugin work with guest accounts, so it's an important fix, even though its not optimal

**Comment by bennothommo** [comment]
I am working on an alternate PR that uses a Rule object instead, so it will be fixed.

**Comment by AIC-BV** [comment]
> 

Is there any news on this? 😄

**Comment by LukeTowers** [comment]
@bennothommo ping 😉

**Comment by bennothommo** [comment]
Thanks for the reminder.

I did have a crack at this months ago, I think I got stopped by the fact we don't support `DataAwareRules` in Storm (https://laravel.com/docs/9.x/validation#using-rule-objects) yet. I need to include support for that in order to make the new rules work (albeit this would mean people would also need to update Winter and this plugin in order to support guests)

**Comment by AIC-BV** [comment]
@LukeTowers @bennothommo @mjauvin 
Guest users are still bugged without this PR.
I have been modifying this file manually for the past years each time it got overwritten by updating.

onRegister triggers a Laravel validation rule that requires the email to be unique.
But if a developer already registered the user as a guest, they can never ever register because of this rule.

I am forced to override this e-mail rule every single time...
Original UserModel rules:
```
public $rules = [
        'email'    => 'required|between:6,255|email|unique:users',
        'avatar'   => 'nullable|image|max:4000',
        'username' => 'required|between:2,255|unique:users',
        'password' => 'required:create|between:8,255|confirmed',
        'password_confirmation' => 'required_with:password|between:8,255',
    ];
```
Overridden rules at components/Account.php
```
$rules = (new UserModel)->rules;
$rules['email'] = 'required|between:6,255|email';
```
Without this, a guest user can never ever register because his 'account' already exists in the users table.
It is expected that a user can register and inherit the guest user data?

-------
Edit:
Either way, we now added our own component that extends Winter/Account and overrides onRegister, but the original bug remains for new developers that actually use Guests.

**Comment by mjauvin** [comment]
@AIC-BV can you test this PR instead?

It addresses @bennothommo's concerns.

**Comment by AIC-BV** [comment]
> @AIC-BV can you test this PR instead?
> 
> It addresses @bennothommo's concerns.

Thanks for the fast feedback @mjauvin 
This looks very promissing. We will test it soon

**Pull request closed without merging**
