### PR TITLE
Update plugin icons

### PR DESCRIPTION
**Pull request by WebVPF**
## sideMenu

Before:
before-usersmenu

After:
after-2

Links to icons in the catalog:
- item Groups: https://fontawesome.com/icons/users-viewfinder?f=classic&s=solid

## Settings menu:

Before:
before-settingsmenu

After:
after-settingsmenu

Link: https://fontawesome.com/icons/user-gear?f=classic&s=solid

### CODE REVIEW

**Comment by LukeTowers** [comment]
@bennothommo any idea what's wrong with the tests on the repo right now?

**Comment by WebVPF** [comment]
I updated the screenshot with the result.

-------
I would also like to suggest changes to the rest of the main menu icons.

October Style:
menu-october-style

Winter Style:
menu-winter-style

No plugins:
menu-noplugins

If the new style suits, I can update all the SVG icons.

**Comment by LukeTowers** [comment]
@WebVPF I really like those! I don't think we should change the dashboard icon to the logo though, end users don't necessarily know or care that their site or platform is running Winter so it's less obvious what exactly that icon means to them. The CMS icon change is also similar in that the original icon was more clear as to what exactly it is (although I do like that new icon, just not sure what it works best for 😄)

**Comment by WebVPF** [comment]
@LukeTowers I agree.
Do you have any remarks on this pull request?

**Review by LukeTowers — APPROVED** [review]

**Comment by LukeTowers** [comment]
Nope, looks great @WebVPF! Thanks!

**Pull request merged**
